version: '3.3'
services:
  backend:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - db
    healthcheck:
      test: curl http://localhost:8080/ || exit 1
      interval: 60s
      retries: 5
      timeout: 10s
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
